version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "springboot-app"
    AWS_DEFAULT_REGION: "us-east-1"
    ACCOUNT_ID: "042167397413"
    REPOSITORY_URI: "042167397413.dkr.ecr.us-east-1.amazonaws.com/springboot-app"

phases:
  install:
    commands:
      - echo "Verifying tools..."
      - mvn -v
      - docker --version

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Building JAR..."
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME .

  post_build:
    commands:
      - echo "Tagging & pushing Docker image..."
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest

      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"springboot-app","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
