version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR"
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - REPO_URI=$ECR_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Building JAR"
      - mvn clean package -DskipTests
      - echo "Building Docker Image"
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing to ECR"
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - printf '[{"name":"springboot-app","imageUri":"%s"}]' "$REPO_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
