version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "springboot-app"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - mvn -v
      - docker --version

  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Current directory is: $(pwd)"
      - ls -la

  build:
    commands:
      - echo "Building JAR..."
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME .

  post_build:
    commands:
      - echo "Tagging & pushing image..."
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
